version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - sudo apt-get update
      - curl -sS https://bootstrap.pypa.io/get-pip.py | sudo python3
      - sudo python3 -m pip install --upgrade pip
      - sudo pip3 install --upgrade setuptools wheel
      - sudo pip3 install -r requirements.txt


