version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - sudo apt-get update
      - sudo apt-get install -y python3-pip
      - pip3 install --upgrade pip
      - pip3 install --upgrade setuptools wheel
      - pip3 install -r requirements.txt


