version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - sudo apt-get update
      - curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
      - python3.10 -m pip install --upgrade pip
      - pip install --upgrade setuptools wheel
      - pip install -r requirements.txt

